services:
  directus:
    image: directus/directus:latest
    container_name: directus
    ports:
      - '8055:8055'
    volumes:
      # Для сохранения БД между перезапусками
      - ./database:/directus/database
      # Для сохранения загруженных файлов
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    restart: always
    env_file:
      - .env
